-- schema for the basic single user DB in PostGreSQL

DROP TYPE IF EXISTS enum_status;
CREATE TYPE enum_status AS ENUM ('pending', 'sent', 'failed');

CREATE TABLE IF NOT EXISTS users (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    userID UUID NOT NULL DEFAULT uuidv7(),
    payload JSONB NOT NULL,
    execute_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deferred_status enum_status NOT NULL DEFAULT 'pending',
    contact_id  JSONB NOT NULL
);

-- educational notes of this in attached md file with same name